version: 2
jobs:
  build:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            docker build -f compose/local/api/Dockerfile -t holidayoffers:local .
            docker run -it holidayoffers:local /app/test.sh

      - run:
          name: build image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -f compose/production/api/Dockerfile -t agrendalath/holiday-offers:${CIRCLE_BRANCH} .
            docker push agrendalath/holiday-offers:${CIRCLE_BRANCH}
